const {
  Events,
  ButtonInteraction,
  EmbedBuilder,
  Client,
} = require("discord.js");

const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "Email",
  key: "Key",
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});
const doc = new GoogleSpreadsheet(
  "Doc",
  serviceAccountAuth
);
module.exports = {
  name: Events.InteractionCreate,
  /**
   *
   * @param {ButtonInteraction} interaction
   * @param {Client} client
   * @returns
   */
  async execute(interaction, client) {
    if (!interaction.isButton()) return;

    if (
      !interaction.message.embeds[0].footer &&
      !interaction.message.embeds[0].footer.text.length === 18
    )
      return;
    await interaction.deferReply({ ephemeral: true });

    const footerText = interaction.message.embeds[0].footer.text;
    await doc.loadInfo();
    const featuredSheet = doc.sheetsById[1883244075];
    await featuredSheet.loadCells("A1:M30");
    const Columns = [
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
    ];

    let columnNum;
    let orgID;
    for (let i = 0; i < 12; i++) {
      const organizerData = featuredSheet.getCellByA1(`${Columns[i]}2`).value;
      const organizerdataSplit = organizerData.split("-");
      orgID = organizerdataSplit[1];
      columnNum = i;
      if (orgID === footerText) break;
    }

    const responseEmbed = new EmbedBuilder()
      .setColor("DarkBlue")
      .setFooter({ text: "😊👌" });

    const buttonNumber = interaction.customId.split("_")[2];
    if (buttonNumber === "1") {
      const buttonName = featuredSheet.getCellByA1(
        `${Columns[columnNum]}6`
      ).value;
      const buttonData = featuredSheet.getCellByA1(
        `${Columns[columnNum]}7`
      ).value;

      responseEmbed.setTitle(`${buttonName}`).setDescription(`${buttonData}`);
      interaction.followUp({ embeds: [responseEmbed], ephemeral: true });
    } else if (buttonNumber === "2") {
      const buttonName = featuredSheet.getCellByA1(
        `${Columns[columnNum]}8`
      ).value;
      const buttonData = featuredSheet.getCellByA1(
        `${Columns[columnNum]}9`
      ).value;

      responseEmbed.setTitle(`${buttonName}`).setDescription(`${buttonData}`);
      interaction.followUp({ embeds: [responseEmbed], ephemeral: true });
    } else if (buttonNumber === "3") {
      const buttonName = featuredSheet.getCellByA1(
        `${Columns[columnNum]}10`
      ).value;
      const buttonData = featuredSheet.getCellByA1(
        `${Columns[columnNum]}11`
      ).value;

      responseEmbed.setTitle(`${buttonName}`).setDescription(`${buttonData}`);
      interaction.followUp({ embeds: [responseEmbed], ephemeral: true });
    } else if (buttonNumber === "4") {
      const buttonName = featuredSheet.getCellByA1(
        `${Columns[columnNum]}12`
      ).value;
      const buttonData = featuredSheet.getCellByA1(
        `${Columns[columnNum]}13`
      ).value;

      responseEmbed.setTitle(`${buttonName}`).setDescription(`${buttonData}`);
      interaction.followUp({ embeds: [responseEmbed], ephemeral: true });
    }
  },
};
